### ISSUE TITLE
Hacktoberfest - Contribute To This Repository!

### ISSUE THREAD

**Issue by samyakbambole** [samyakbambole/twitch-live-chat-history#1]
You can fix some bugs, add some improvements or something that you think can improve this project. Happy Coding and Contributing! 🌈

**Comment by Yukta-Jaiswal** [comment]
Can you describe what is to be done?

**Comment by samyakbambole** [comment]
Refer The [Contributing.,md](https://github.com/samyakbambole/twitch-live-chat-history/blob/master/CONTRIBUTING.md) and The [Readme](https://github.com/samyakbambole/twitch-live-chat-history/)

**Comment by samyakbambole** [comment]
> Can you describe what is to be done?

This Node.js App could be used for Saving the history of Twitch Live Streams

**Comment by samyakbambole** [comment]
@Yukta-Jaiswal You can fix some bugs, add some improvements or something that you think can improve this project. Happy Coding and Contributing! 🌈

**Comment by samyakbambole** [comment]
# Whoever Contributes to this Open Source Project, They will get their name in the Board of Contributors in the Readme!
