### ISSUE TITLE
Error in App

### ISSUE THREAD

**Issue by samyakbambole** [samyakbambole/twitch-live-chat-history#12]
@symtalha14 The Chagnes you made, were good but When I tried to get the chats of multiple streamers, Only the first Streamer's Chats appear. I request you to fix this.

**Comment by samyakbambole** [comment]
please fix this someone

**Comment by samyakbambole** [comment]
Please fix this as soon as possible

**Comment by symtalha14** [comment]
It went fine on my local one. I'll see it No problem.

**Comment by symtalha14** [comment]
Hey, I just checked it. It's working absolutely fine.
![Screenshot (100)](https://user-images.githubusercontent.com/26308379/95052578-cd484680-070c-11eb-9f02-f74f4fabcadb.png)

**Comment by symtalha14** [comment]
Maybe the channels you checked...one of them was having far more frequent msgs than the other one.

**Comment by samyakbambole** [comment]
Ok I will check that

**Comment by samyakbambole** [comment]
For now Im Closing the issue, if this error continues, I may repoen it.

**Comment by symtalha14** [comment]
> For now Im Closing the issue, if this error continues, I may repoen it.

Sure! Just check whether it's function properly.
