### ISSUE TITLE
Can we Add emoji Support?

### ISSUE THREAD

**Issue by samyakbambole** [samyakbambole/twitch-live-chat-history#14]

**Comment by samyakbambole** [comment]
There are a lot of Default Emojis in Twitch. So Can we show them in the web interface?

**Comment by samyakbambole** [comment]
@nicolashacala , @jpiazzal Can you Help?

**Comment by samyakbambole** [comment]
Everyone Can Contribute!

**Comment by erdemuslu** [comment]
I'm working on it.

**Comment by samyakbambole** [comment]
> I'm working on it.

Good! 😀👍

**Comment by erdemuslu** [comment]
#16 I added them.

**Comment by samyakbambole** [comment]
Can You Please Send me some screenshots. I'll need to verify it first.

**Comment by erdemuslu** [comment]
Yeah, sure.

Screenshot:
https://i.ibb.co/pK7DZQ2/test.png

Video:
https://streamable.com/0hpiyd

**Comment by samyakbambole** [comment]
Ok!

**Comment by samyakbambole** [comment]
The PR is merged @erdemuslu .
