### ISSUE TITLE
Bug in index.js

### ISSUE THREAD

**Issue by samyakbambole** [samyakbambole/twitch-live-chat-history#21]
When I run the app, The messages are `console.log`ed 5 times. The database also has 5 entries for a message and the Web interface also displays one message 5 times.

**Comment by samyakbambole** [comment]
If you can help, feel free to contribute and make a PR!

**Comment by sarawukl** [comment]
In this case occurred when you refresh the page?

**Comment by sarawukl** [comment]
I'm working on this issue, Could you assign to me please?

**Comment by samyakbambole** [comment]
> I'm working on this issue, Could you assign to me please?

Feel free to contribute!

**Comment by sarawukl** [comment]
> > I'm working on this issue, Could you assign to me please?
> 
> Feel free to contribute!

Please review my commit. #25
