### ISSUE TITLE
Add Option to remove a Twitch Channel in the Web Interface. 

### ISSUE THREAD

**Issue by samyakbambole** [samyakbambole/twitch-live-chat-history#26]
As We can add channels through the web interface, We Should also be able to remove those channels.

**Comment by samyakbambole** [comment]
@sarawukl see if you can Help!

**Comment by sarawukl** [comment]
Okay, I will try on this. 😁

**Comment by samyakbambole** [comment]
> Okay, I will try on this. 😁

👍

**Comment by sarawukl** [comment]
> This Must be possible with socket.io Right?

If you want to remove the channel with socket.io, You need to connect to Twitch message for each user. 

Please review my pr #28
