### ISSUE TITLE
Can we make a Website to show all the chats?

### ISSUE THREAD

**Issue by samyakbambole** [samyakbambole/twitch-live-chat-history#7]
If we can do that (with tmi.js) save all the files (index.html, styles.css, index.js) in the `web` folder / directory.

**Comment by samyakbambole** [comment]
The PR made by @nicolashacala was great! but can we get autoscrolling and some more styles?

**Comment by symtalha14** [comment]
Hello, I've made a PR. Please check it. I've modified the way the messages are shown.

**Comment by samyakbambole** [comment]
> Hello, I've made a PR. Please check it. I've modified the way the messages are shown.

Done!
